language: go
sudo: false
go:
- 1.8

env:
  global:
    secure: KhhUmj2Y+EARBrOPSYaRYcNJeFnVk1dnQcI1rP2nGL6nGu7jjGH3Nf7bPPDzgPo0fKbo4TjXxqt03ny3X4TD7nl95jFEePZ7WIQOYJ/nQZqi7qvwNkCk7J4kJYctwF3Daj03v8edRwjqarpRGXks35fjEpxuhlMyLskAUUi7Bz8uBK4ccsCcItK8WUCewkIwjVLF7prbq+WZNrrXKbKcC7Xk/Bl2284wwQUdZqbRb64lg6G4V0azZPrDL5Lb8IirtV8kEk7Yw+MUFPBU/ArjXmC9WydzGFZ92Wg9LRyos/m9gQEOLooqMUmEf4odNj5eEHjU1pmsPDTcWFt5rHO17b04RP/XB1SOKVsSYilhfrf0cTTYVqs2t7DObeZvzd3uGiy7lAs2Wh+FiD6xgH56RUDWVhb8mNpLdvxT1dQvboeV/8Bfx2t6oLT1pzRa7ZFhY/lJt/GOvCkju9vzTkR7RXwYyVYmp7DJUJJ7MTF3XIA2c4mKAdP8GiCSlWWQzm0dVIk1DJBjW6EusYv4vkKyQKXV1XrlNv4WgYanwlAMZ/sEsVBM1pj+D+Dz5fW37wrg5tzUFK9xbaAfDigc+ICqJJtWGYpm4ZA8+ZtHgNF/nmuVAu5FIV6TSLiqMpNvc6OazvK7nU1O8Odf7YyG4fwuUXfDjI34jrK0eo/9OjJa2zA=

addons:
  apt:
    packages: rpm
install:
- gem install fpm
script:
- make prepare
- make build
- make rpm
before_deploy:
- export PACKAGE_NAME=$(ls build/oauth2-proxy-*.x86_64.rpm | tail -n1)
deploy:
- provider: script
  script: "curl -sS --fail -F \"uploadfile=@${PACKAGE_NAME}\" -H 'token: ${UPLOAD_TOKEN}' \"${UPLOAD_URL}\""
  skip_cleanup: true
  on:
    branch: master
    condition: "$TRAVIS_GO_VERSION = 1.8"
- provider: script
  script: "curl -sS --fail -F \"uploadfile=@${PACKAGE_NAME}\" -H 'token: ${UPLOAD_TOKEN}' \"${UPLOAD_URL}\""
  skip_cleanup: true
  on:
    tags: true
    condition: "$TRAVIS_GO_VERSION = 1.8"
